services:
  browser-use-vnc:
    build: .
    ports:
      - "5900:5900"  # VNC
      - "6080:6080"  # noVNC
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - DISPLAY=:99
    restart: unless-stopped
