version: "3.9"

services:
  vnc:
    build: .
    environment:
      - DISPLAY=:99
      - SESSION_ID=${SESSION_ID}
      - NOVNC_PORT=${NOVNC_PORT}
    ports:
      - "${NOVNC_PORT}:6080"   # 예: 6081, 6082, ...
    labels:
      - "bu.session=${SESSION_ID}"
      - "bu.role=vnc"
    volumes:
      - x11sock:/tmp/.X11-unix

  agent:
    build:
      context: ../agent
      dockerfile: Dockerfile
    env_file:
      - ${ENV_FILE:-../agent/.env}  # agent 용 .env
    environment:
      - DISPLAY=:99
      - SESSION_ID=${SESSION_ID}
      # TASK_PROMPT 미사용 → 환경변수 전달 제거
    labels:
      - "bu.session=${SESSION_ID}"
      - "bu.role=agent"
    volumes:
      - x11sock:/tmp/.X11-unix
    depends_on: [vnc]
    command: ["python","agent.py"]   # agent 진입점

volumes:
  x11sock: